import Head from "next/head";
import { useRouter } from "next/router";
import Recent from "../components/recent";

export default function Home() {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>College-Codes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Recent />

      {/* <footer></footer> */}
    </div>
  );
}
