import Head from 'next/head'

import Compiler from '../components/compiler'

export default function Home() {
  return (
    <div>
      <Head>
        <title>College-Codes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Compiler /> */}
      <h1>heocnnl</h1>

      <footer></footer>
    </div>
  )
}
